[Setup]
Product=YourProductNameCodeTODO
Language=int
Version=1
Exe=System\UE2Runtime.exe
CdAutoPlay=True
IsMasterProduct=True
Patch=False
Tree=True
SrcPath=..\%Product%-%Version%\
MasterPath=..
MasterPathContent=..
Visible=True
Group=SetupGroup
Group=ProjectGroup
Group=ContentGroup
;EditorGroup is optinal. Remove this line if you do not want your project to ship with the editing tools
Group=EditorGroup
License=License.int

[SetupGroup]
Copy=(Src=System\License.*)
Copy=(Src=System\Manifest.*,Flags=3)
Backup=System\Core.dll
Backup=System\VorbisFile.dll
Backup=System\IFC23.dll
Backup=System\Core.int
Backup=System\Core.%Language%
Backup=System\Engine.dll
Backup=System\Engine.int
Backup=System\Engine.%Language%
Backup=System\Window.dll
Backup=System\Window.int
Backup=System\Window.%Language%
Backup=System\Setup.exe
Backup=System\SetupStrings.int
Backup=System\Setup.%Language%
Backup=System\Manifest.ini
Backup=System\MSVCR71.dll
Backup=System\MSVCR70.dll
Backup=Help\InstallerLogo.bmp
Delete=System\Detected.log
Delete=System\Detected.ini
Delete=System\UE2Runtime.log
Delete=System\Editor.log
Backup=System\Ogg.dll
Backup=System\Vorbis.dll
WinRegistry=HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\CurrentVersion\Uninstall\%Product%\DisplayName=%LocalProduct%
WinRegistry=HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\CurrentVersion\Uninstall\%Product%\UninstallString=%DestPath%\System\Setup.exe uninstall "%Product%"

[HelpGroup]
File=(Src=Help\UE2Runtime.ico)
;File=(Src=Help\YourProductTODO.ico)
File=(Src=Help\UnrealEd.ico)
;File=(Src=Help\YourProductReadmeTODO.txt,Master=Help\YourProductReadmeTODO.txt)
;File=(Src=Help\YourProductLogoTODO.bmp,Master=Help\YourProductLogoTODO.bmp)
;File=(Src=Help\YourProductInstallerLogoTODO.bmp,Master=Help\YourProductInstallerLogoTODO.bmp)
;File=(Src=System\YourProductTODO.url)


[EngineSystemGroup]
File=(Src=System\Core.u)
File=(Src=System\Core.dll)
File=(Src=System\Core.int)
File=(Src=System\D3DDrv.dll)
File=(Src=System\D3DDrv.int)
File=(Src=System\Engine.dll)
File=(Src=System\Engine.int)
File=(Src=System\Engine.u)
File=(Src=System\Editor.u)
File=(Src=System\Fire.dll)
File=(Src=System\Fire.u)
File=(Src=System\IpDrv.dll)
File=(Src=System\IpDrv.int)
File=(Src=System\IpDrv.u)
File=(Src=System\MSVCR71.dll)
File=(Src=System\MSVCR70.dll)
File=(Src=System\RunServer.bat)
File=(Src=System\Setup.exe)
File=(Src=System\Setup.int,Master=System\SetupStrings.int)
File=(Src=System\Startup.int)
File=(Src=System\UCC.exe)
File=(Src=System\Window.dll)
File=(Src=System\Window.int)
File=(Src=System\WinDrv.dll)
File=(Src=System\WinDrv.int)
File=(Src=System\Ogg.dll)
File=(Src=System\Vorbis.dll)
File=(Src=System\VorbisFile.dll)
File=(Src=System\ALAudio.dll)
File=(Src=System\UnrealEd.u)
File=(Src=System\DefOpenAL32.dll)
File=(Src=System\IFC23.dll)
File=(Src=System\Gameplay.u)
File=(Src=System\GUI.u)
File=(Src=System\GUI.dll)
File=(Src=System\UWeb.u)
File=(Src=System\Runtime.u)
File=(Src=System\RTInterface.u)
File=(Src=System\RTInterface.int)
File=(Src=System\Packages.md5)
File=(Src=System\PixoDrv.dll)
File=(Src=System\Pixomatic.dll)

[ProjectGroup]
File=(Src=System\UE2Runtime.exe)
File=(Src=System\UE2Runtime.int)
File=(Src=System\UWeb.int)
File=(Src=System\UWeb.u)
File=(Src=System\UWeb.dll)
File=(Src=System\Gameplay.u)
File=(Src=System\DefUser.ini,         Master=System\DefUser.ini)
File=(Src=System\Default.ini,         Master=System\Default.ini)
File=(Src=System\UnrealEdTips.ini,    Master=System\UnrealEdTips.ini)
File=(Src=System\UDNHelpTopics.ini,   Master=System\UDNHelpTopics.ini)
File=(Src=System\DefUnrealEd.ini,     Master=System\DefUnrealEd.ini)
File=(Src=Maps\Entry.urt)
File=(Src=Textures\GUIContent.utx)
File=(Src=Textures\EM_Fonts_T.utx)
File=(Src=Textures\RuntimeInterfaceContent.utx)
File=(Src=Textures\RT_BoxSkins_T.utx)
File=(Src=Sounds\RuntimeInterfaceSounds.uax)
File=(Src=Animations\RT_Box_K.ukx)
File=(Src=Web\*.uhtm,MasterRecurse=True)
File=(Src=Web\*.gif,MasterRecurse=True)
; TODO Add/remove files that are required to run your project here

Ini=System\Default.ini,Engine.Engine.Language=%Language%

[ContentGroup]
MasterPath=%MasterPathContent%
Ini=!System\Default.ini,Engine.Engine.ContentOnCD=True
; TODO Put the project content here. Specifically, Maps, StaticMeshes and their Textures should be listed here
; Example:
; File=(Src=Maps\MainMap.urt)

[ProjectGroup]
Optional=False
Visible=True
Group=EngineSystemGroup
Group=ContentGroup
Group=HelpGroup
Folder=Maps
Folder=Textures
Folder=StaticMeshes
Folder=Prefabs
Folder=Sounds
Folder=Music
Shortcut=PlayShortcut
Shortcut=SafeModeShortcut
Shortcut=WebShortcut
Shortcut=EditorShortcut
Shortcut=UninstallShortcut
WinRegistry=HKEY_LOCAL_MACHINE\Software\Unreal Technology\Installed Apps\%Product%\Folder=%DestPath%
WinRegistry=HKEY_LOCAL_MACHINE\Software\Unreal Technology\Installed Apps\%Product%\Version=%Version%

[EditorGroup]
Optional=False
Visible=False
Selected=True
File=(Src=System\UnrealEd.exe)
File=(Src=System\DefUnrealEd.ini,         Master=System\DefUnrealEd.ini)
File=(Src=System\DefUser.ini,            Master=System\DefUser.ini)
File=(Src=System\UnrealEd.int)
File=(Src=System\Editor.dll)
File=(Src=System\Editor.int)
File=(Src=System\Editor.u)
File=(Src=System\editorres\*.*)
File=(Src=System\edsplash.bmp)
File=(Src=System\dinterface.dll)
File=(Src=System\udebugger.exe)
File=(Src=Help\DebuggerLogo.bmp)

[PlayShortcut]
Template=%CommonProgramsPath%\%LocalProduct%\%Caption%.lnk
WorkingDirectory=%DestPath%\System
Command=%DestPath%\%Exe%
Parameters=
Icon=%DestPath%\Help\YourProductTOOD.ico

[SafeModeShortcut]
Template=%CommonProgramsPath%\%LocalProduct%\%Caption%.lnk
WorkingDirectory=%DestPath%\System
Command=%DestPath%\%Exe%
Parameters=-safe
Icon=%DestPath%\Help\YourProductTOOD.ico

[UninstallShortcut]
Template=%CommonProgramsPath%\%LocalProduct%\%Caption%.lnk
WorkingDirectory=%DestPath%\System
Command=%DestPath%\System\Setup.exe
Parameters=uninstall "%Product%"
Icon=%DestPath%\System\Setup.exe,0

[EditorShortcut]
Template=%CommonProgramsPath%\%LocalProduct%\%Caption%.lnk
WorkingDirectory=%DestPath%\System
Command=%DestPath%\System\UnrealEd.exe
Parameters=
Icon=%DestPath%\Help\UnrealEd.ico

[WebShortcut]
Template=%CommonProgramsPath%\%LocalProduct%\%Caption%.lnk
WorkingDirectory=%DestPath%\System
Command=%DestPath%\System\YourProductTODO.url
Parameters=
Icon=